export const users = [
  {
    id: 1,
    name: "Ava Jones",
    description:"It would be wonderful to meet someone who appreciates the arts and enjoys exploring the vibrant culture of the city. I value open-mindedness, good communication, and a shared passion for classical music and fine arts. Also, mother of 2 cats ;)",
    location: "Las Vegas, NV 89104",
    job:"Business Analyst at Tech",
    distance: 11,
    age: 25,
    image: require("../assets/user1.jpg"),
    height: 168,
    enjoy: [
      "Classical Music & Art",
      "Thriller Films",
      "Nature",
      "Ranking",
      "Asian Food",
      "Mathematics & Technology",
    ],
    languages: [
      "English(Native)",
      "Spanish(Fluent)",
      "Tagalog(Verbal)",
      "Mandarin Chinese(Verbial)",
    ],
    subImage: [
      "https://i.pinimg.com/originals/05/bc/68/05bc682857582a6b52bbdb12e3b896b0.jpg",
      "https://i.pinimg.com/originals/05/bc/68/05bc682857582a6b52bbdb12e3b896b0.jpg",
      "https://i.pinimg.com/originals/05/bc/68/05bc682857582a6b52bbdb12e3b896b0.jpg",
    ],
  },
  {
    id: 2,
    name: "William Ida",
    description:"It would be wonderful to meet someone who appreciates the arts and enjoys exploring the vibrant culture of the city. I value open-mindedness, good communication, and a shared passion for classical music and fine arts. Also, mother of 2 cats ;)",
    location: "Portland illinois",
    job:"Business Analyst at Tech",
    distance: 11,
    age: 24,
    image: require("../assets/user2.jpg"),
    height: 168,
    enjoy: [
      "Classical Music & Art",
      "Thriller Films",
      "Nature",
      "Ranking",
      "Asian Food",
      "Mathematics & Technology",
    ],
    languages: [
      "English(Native)",
      "Spanish(Fluent)",
      "Tagalog(Verbal)",
    ],
    subImage: [
      "https://i.pinimg.com/originals/05/bc/68/05bc682857582a6b52bbdb12e3b896b0.jpg",
      "https://i.pinimg.com/originals/05/bc/68/05bc682857582a6b52bbdb12e3b896b0.jpg",
      "https://i.pinimg.com/originals/05/bc/68/05bc682857582a6b52bbdb12e3b896b0.jpg",
    ],
  },
  {
    id: 3,
    name: "Tracy Fradera",
    location: "Portland illinois",
    job:"Business Analyst at Tech",
    distance: 11,
    age: 24,
    image: require("../assets/user3.jpg"),
  },
  {
    id: 4,
    name: "Doreatha Grave",
    location: "Portland illinois",
    job:"Business Analyst at Tech",
    distance: 11,
    age: 24,
    image: require("../assets/user4.jpg"),
  },
  {
    id: 5,
    name: "Jacquetta Bobalik",
    location: "Portland illinois",
    job:"Business Analyst at Tech",
    distance: 11,
    age: 24,
    image: require("../assets/user5.jpg"),
  },
  {
    id: 6,
    name: "Velia Kwasniak",
    location: "Portland illinois",
    job:"Business Analyst at Tech",
    distance: 11,
    age: 24,
    image: require("../assets/user6.jpg"),
  },
  {
    id: 7,
    name: "Karisa Delorm",
    location: "Portland illinois",
    job:"Business Analyst at Tech",
    distance: 11,
    age: 24,
    image: require("../assets/user7.jpg"),
  },
  {
    id: 8,
    name: "Cecil Agudelo",
    location: "Portland illinois",
    job:"Business Analyst at Tech",
    distance: 11,
    age: 24,
    image: require("../assets/user8.jpg"),
  },
];
